{"name": "Проверить, что вернется сообщение об ошибке при незаполненном поле", "status": "passed", "start": 1723750641439, "stop": 1723750641815, "uuid": "23a414cc-8e0e-4729-9d42-c4b3a986a4e3", "historyId": "603c9367788ff014c39d45484caef141", "testCaseId": "603c9367788ff014c39d45484caef141", "fullName": "tests.test_cuorier_login.TestCourierLogin#test_login_courier_missing_field", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cuorier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-C0DAUU0"}, {"name": "thread", "value": "13260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cuorier_login"}]}